export const customers = [
  {
    id: '1',
    name: 'Baumann Versicherungen GmbH',
    contact_name: 'Angelika Baumann',
    phone: 1652348790,
    email: 'abaumann@abvs.de',
    address: {
      street: 'Müllerallee 78',
      city: 'Berlin',
      zip: 12119,
    },
    industry: 'Versicherungswesen',
    type: 'firma',
    orders: ['Telefonanlage', 'CRM', 'Cloud-Umgebung'],
    invoices: ['Rechnung #1', 'Rechnung #2', 'Rechnung #3'],
    first_order_date: new Date(),
    status: 'aktiv',
  },
  {
    id: '2',
    name: 'ImmoSchmidt',
    contact_name: 'Michael Schmidt',
    phone: 1598723495,
    email: 'michaelschmidt@web.de',
    address: {
      street: 'Hauptstraße 23',
      city: 'Berlin',
      zip: 10125,
    },
    industry: 'Immobilien',
    type: 'firma',
    orders: ['Email-Archivierung', 'Sicherung IT-Systeme'],
    invoices: ['Rechnung #1', 'Rechnung #2'],
    first_order_date: new Date(),
    status: 'aktiv',
  },
  {
    id: '3',
    name: 'Bücherwelt Meier',
    contact_name: 'Sven Meier',
    phone: 1598723495,
    email: 'svemmeier@buecherwelt.de',
    address: {
      street: 'Gartenstraße 14',
      city: 'Berlin',
      zip: 10117,
    },
    industry: 'Einzelhandel',
    type: 'firma',
    orders: ['Microsoft 365', 'Bestellsystem'],
    invoices: ['Rechnung #1'],
    first_order_date: new Date(),
    status: 'aktiv',
  },
];
