import { Customer } from './customers/customer.entity';

export const customers: Customer[] = [
  {
    id: 1,
    name: 'Baumann Versicherungen GmbH',
    contactName: 'Angelika Baumann',
    phone: 1652348790,
    email: 'abaumann@abvs.de',
    street: 'Müllerallee 78',
    city: 'Berlin',
    zipcode: 12119,
    industry: 'Versicherungswesen',
    type: 'firma',
    orders: "['Telefonanlage', 'CRM', 'Cloud-Umgebung']",
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
  },
  {
    id: 2,
    name: 'ImmoSchmidt',
    contactName: 'Michael Schmidt',
    phone: 1598723495,
    email: 'michaelschmidt@web.de',
    street: 'Hauptstraße 23',
    city: 'Berlin',
    zipcode: 10125,
    industry: 'Immobilien',
    type: 'firma',
    orders: "['Email-Archivierung', 'Sicherung IT-Systeme']",
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
  },
  {
    id: 3,
    name: 'Bücherwelt Meier',
    contactName: 'Sven Meier',
    phone: 1598723495,
    email: 'svemmeier@buecherwelt.de',
    street: 'Gartenstraße 14',
    city: 'Berlin',
    zipcode: 10117,
    industry: 'Einzelhandel',
    type: 'firma',
    orders: "['Microsoft 365', 'Bestellsystem']",
    invoices: "['Rechnung #1']",
    firstOrderDate: new Date(),
    status: 'aktiv',
  },
];
