import { Customer } from '../../../client/src/app/models/customer';

export const customers: Customer[] = [
  {
    id: 1,
    name: 'Koch Metallbau GmbH',
    contactName: 'Ralf Koch',
    phone: 1734598271,
    email: 'rkoch@koch-metallbau.de',
    street: 'Werkstraße 5',
    city: 'Hamburg',
    zipcode: 22081,
    industry: 'Metallverarbeitung',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Bitte nur per E-Mail kontaktieren.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 2,
    name: 'Blumen Rieger OHG',
    contactName: 'Sandra Rieger',
    phone: 1624890375,
    email: 'srieger@blumenrieger.de',
    street: 'Marktplatz 12',
    city: 'München',
    zipcode: 80331,
    industry: 'Einzelhandel',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes:
      'Frau Rieger im Juli nicht erreichbar, Ansprechpartner: Herr Baumgart.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 3,
    name: 'Schneider IT-Service',
    contactName: 'Tobias Schneider',
    phone: 1759201846,
    email: 'tschneider@schneider-it.de',
    street: 'Bahnhofstraße 44',
    city: 'Leipzig',
    zipcode: 14109,
    industry: 'IT-Dienstleistungen',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3', 'Rechnung #4']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Langjähriger Kunde, Sonderkonditionen vereinbart.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 4,
    name: 'Müller & Sohn Bäckerei KG',
    contactName: 'Karin Müller',
    phone: 1712839401,
    email: 'kmueller@baeckerei-mueller.de',
    street: 'Bäckerweg 9',
    city: 'Köln',
    zipcode: 50667,
    industry: 'Lebensmittelhandwerk',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes:
      'Letzte Lieferung verspätet – Kunde unzufrieden, Gutschrift angeboten.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 5,
    name: 'Autohaus Lehmann GmbH',
    contactName: 'Thomas Lehmann',
    phone: 1604389274,
    email: 'tlehmann@auto-lehmann.de',
    street: 'Autoring 22',
    city: 'Hannover',
    zipcode: 30159,
    industry: 'Automobilhandel',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Support-Anfrage bzgl. Rechnung #3 noch offen.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 6,
    name: 'Praxis Dr. Neumann',
    contactName: 'Dr. Anke Neumann',
    phone: 1762840913,
    email: 'dr.neumann@praxis-neumann.de',
    street: 'Lindenallee 3',
    city: 'Frankfurt am Main',
    zipcode: 60311,
    industry: 'Gesundheitswesen',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Interesse an Cloud-Service geäußert.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 7,
    name: 'Zimmerei Hoffmann',
    contactName: 'Stefan Hoffmann',
    phone: 1774509213,
    email: 'shoffmann@zimmerei-hoffmann.de',
    street: 'Holzweg 17',
    city: 'Dresden',
    zipcode: 11067,
    industry: 'Handwerk',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Kunde wird von Account Managerin Lisa betreut.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 8,
    name: 'Weinhandlung Krüger',
    contactName: 'Helene Krüger',
    phone: 1598340267,
    email: 'hkrueger@weinhandlung-krueger.de',
    street: 'Altstadtgasse 11',
    city: 'Heidelberg',
    zipcode: 69117,
    industry: 'Einzelhandel',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Wartungsvertrag läuft bis 30.06.2026.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 9,
    name: 'Elektro Schuster GmbH',
    contactName: 'Daniel Schuster',
    phone: 1785620394,
    email: 'dschuster@elektro-schuster.de',
    street: 'Technikstraße 6',
    city: 'Stuttgart',
    zipcode: 70173,
    industry: 'Elektrotechnik',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Termin am Montag auf Mittwoch, 16 Uhr verschoben.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 10,
    name: 'Kreativagentur Weiss',
    contactName: 'Laura Weiss',
    phone: 1705629834,
    email: 'laura.weiss@kreativagentur-weiss.de',
    street: 'Neustadtstraße 8',
    city: 'Bremen',
    zipcode: 28195,
    industry: 'Marketing & Design',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Rechnung #3 musste nachkorrigiert werden (falsche MwSt)',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 11,
    name: 'Baumann Versicherungen GmbH',
    contactName: 'Angelika Baumann',
    phone: 1652348790,
    email: 'abaumann@abvs.de',
    street: 'Müllerallee 78',
    city: 'Berlin',
    zipcode: 12119,
    industry: 'Versicherungswesen',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2', 'Rechnung #3']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Besonderer Rabattvertrag über 10 % bis Ende 2025.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 12,
    name: 'ImmoSchmidt',
    contactName: 'Michael Schmidt',
    phone: 1598723495,
    email: 'michaelschmidt@web.de',
    street: 'Hauptstraße 23',
    city: 'Berlin',
    zipcode: 10125,
    industry: 'Immobilien',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Neue Filiale eröffnet im März 2025 – evtl. Zusatzauftrag.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 13,
    name: 'Bücherwelt Meier',
    contactName: 'Sven Meier',
    phone: 1598723495,
    email: 'svemmeier@buecherwelt.de',
    street: 'Gartenstraße 14',
    city: 'Berlin',
    zipcode: 10117,
    industry: 'Einzelhandel',
    type: 'firma',
    invoices: "['Rechnung #1']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes: 'Kunde ruft bevorzugt vormittags an.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
  {
    id: 14,
    name: 'Meyer Bauunternehmen GmbH',
    contactName: 'Johannes Meyer',
    phone: 1712345678,
    email: 'j.meyer@meyerbau.de',
    street: 'Bauhofstraße 9',
    city: 'Dortmund',
    zipcode: 44137,
    industry: 'Bauwirtschaft',
    type: 'firma',
    invoices: "['Rechnung #1', 'Rechnung #2']",
    firstOrderDate: new Date(),
    status: 'aktiv',
    notes:
      'Langjähriger Kunde. Hat Interesse an digitalem Baustellenmanagement geäußert.',
    user: {
      id: 1,
      username: 'user',
      email: 'user@user.de',
      password: '12345678',
      customers: [],
      createdAt: new Date(),
      details: '',
    },
  },
];
