import { Order } from 'src/orders/order.entity';
import { customers } from './customers';

export const orders: Order[] = [
  {
    id: 1,
    title: 'Cloud Umgebung',
    customer: customers[0],
    items: '["Lieferung Hardware", "Installation", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-10'),
    dueDate: new Date('2025-11-10'),
    status: 'in Bearbeitung',
    details: 'Serverzugänge vom Kunden erhalten, Testphase läuft bis 05.11.',
  },
  {
    id: 2,
    title: 'ERP-System',
    customer: customers[0],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-18'),
    dueDate: new Date('2025-11-12'),
    status: 'in Bearbeitung',
    details: 'Schnittstelle zur Buchhaltung wird noch abgestimmt.',
  },
  {
    id: 3,
    title: 'Server-Backup',
    customer: customers[0],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Termin für Vor-Ort-Termin mit Kunde noch offen.',
  },
  {
    id: 4,
    title: 'Datensicherung',
    customer: customers[1],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-9-26'),
    dueDate: new Date('2025-10-12'),
    status: 'abgeschlossen',
    details: 'System erfolgreich abgenommen, Backup läuft täglich automatisch.',
  },
  {
    id: 5,
    title: 'Server-Backup',
    customer: customers[1],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-20'),
    dueDate: new Date('2025-10-23'),
    status: 'abgeschlossen',
    details: 'Kunde zufrieden, zusätzliche Speichererweiterung geplant.',
  },
  {
    id: 6,
    title: 'Email-Archivierung',
    customer: customers[2],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-12'),
    dueDate: new Date('2025-10-19'),
    status: 'storniert',
    details:
      'Projekt storniert, Kunde hat sich für externen Anbieter entschieden.',
  },
  {
    id: 7,
    title: 'Sicherheits-Analyse',
    customer: customers[3],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-11'),
    dueDate: new Date('2025-10-25'),
    status: 'abgeschlossen',
    details: 'Bericht über Sicherheitslücken wurde übergeben.',
  },
  {
    id: 8,
    title: 'Server-Backup',
    customer: customers[3],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-9-30'),
    dueDate: new Date('2025-10-19'),
    status: 'abgeschlossen',
    details:
      'Backup-Plan erfolgreich implementiert, wöchentliche Kontrolle eingerichtet.',
  },
  {
    id: 9,
    title: 'Anti-Phishing Training',
    customer: customers[4],
    items:
      '["Besprechung", "Planung & Vorbereitung", "Durchführung", "Nachbesprechung"]',
    orderDate: new Date('2025-10-10'),
    dueDate: new Date('2025-11-10'),
    status: 'in Bearbeitung',
    details:
      'Schulungstermine mit IT-Abteilung abgestimmt, Präsentation in Vorbereitung.',
  },
  {
    id: 10,
    title: 'ERP-System',
    customer: customers[4],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-18'),
    dueDate: new Date('2025-11-12'),
    status: 'in Bearbeitung',
    details: 'Modul "Lagerverwaltung" wird aktuell implementiert.',
  },
  {
    id: 11,
    title: 'Server-Backup',
    customer: customers[5],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Warten auf Freigabe durch IT-Leitung des Kunden.',
  },
  {
    id: 12,
    title: 'Datensicherung',
    customer: customers[5],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Standort für Backup-Server muss noch bestätigt werden.',
  },
  {
    id: 13,
    title: 'Server-Backup',
    customer: customers[6],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Hardware bereits geliefert, Installation geplant für 05.11.',
  },
  {
    id: 14,
    title: 'Email-Archivierung',
    customer: customers[6],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Zugangsdaten für Mailserver stehen noch aus.',
  },
  {
    id: 15,
    title: 'Sicherheits-Analyse',
    customer: customers[7],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Audit-Termin mit Kunden für 07.11. vereinbart.',
  },
  {
    id: 16,
    title: 'Server-Backup',
    customer: customers[8],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Lizenzschlüssel vom Hersteller wird noch benötigt.',
  },
  {
    id: 17,
    title: 'Nextcloud',
    customer: customers[8],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details:
      'Benutzerkonten sollen mit Active Directory synchronisiert werden.',
  },
  {
    id: 18,
    title: 'Datensicherung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Testlauf für Backup-Restore wird am 12.11. durchgeführt.',
  },
  {
    id: 19,
    title: 'IT-Beratung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Strategieworkshop für IT-Roadmap am 10.11. geplant.',
  },
  {
    id: 20,
    title: 'Email-Archivierung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Konfiguration erfolgt nach Abschluss des ERP-Projekts.',
  },
  {
    id: 21,
    title: 'Telefonanlage',
    customer: customers[10],
    items: '["Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Kunde wünscht zusätzlich Mobilintegration.',
  },
  {
    id: 22,
    title: 'Microsoft 365',
    customer: customers[10],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Lizenztransfer von altem Account noch offen.',
  },
  {
    id: 23,
    title: 'Anti-Phishing Training',
    customer: customers[10],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Trainingstermin mit Belegschaft auf 14.11. terminiert.',
  },
  {
    id: 24,
    title: 'Server-Backup',
    customer: customers[11],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Testumgebung wird derzeit vorbereitet.',
  },
  {
    id: 25,
    title: 'Sicherheits-Analyse',
    customer: customers[11],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Netzwerkscan abgeschlossen, Bericht in Arbeit.',
  },
  {
    id: 26,
    title: 'Telefonanlage',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Lieferung der Geräte für KW45 erwartet.',
  },
  {
    id: 27,
    title: 'Sicherheits-Analyse',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Analyse der Firewall-Konfiguration steht noch aus.',
  },
  {
    id: 28,
    title: 'Server-Backup',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Backup-Zeitplan soll täglich um 23:00 laufen.',
  },
  {
    id: 29,
    title: 'Remote Desktop',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'VPN-Zugangsdaten müssen noch eingerichtet werden.',
  },
  {
    id: 30,
    title: 'Server-Backup',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Testlauf des Backups für 06.11. angesetzt.',
  },
  {
    id: 31,
    title: 'Nextcloud',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'SSL-Zertifikate werden vor Deployment erstellt.',
  },
  {
    id: 32,
    title: 'Monitoring-System',
    customer: customers[14],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Dashboard soll Echtzeit-Alerts per Mail ausgeben.',
  },
  {
    id: 33,
    title: 'Email-Archivierung',
    customer: customers[14],
    items: '["Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: 'Altdatenübernahme aus PST-Dateien erforderlich.',
  },
];
