import { Order } from 'src/orders/order.entity';
import { customers } from './customers';

export const orders: Order[] = [
  {
    id: 1,
    title: 'Cloud Umgebung',
    customer: customers[0],
    items: '["Lieferung Hardware", "Installation", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-10'),
    dueDate: new Date('2025-11-10'),
    status: 'in Bearbeitung',
    details: '',
  },
  {
    id: 2,
    title: 'ERP-System',
    customer: customers[0],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-18'),
    dueDate: new Date('2025-11-12'),
    status: 'in Bearbeitung',
    details: '',
  },
  {
    id: 3,
    title: 'Server-Backup',
    customer: customers[0],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 4,
    title: 'Datensicherung',
    customer: customers[1],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-9-26'),
    dueDate: new Date('2025-10-12'),
    status: 'abgeschlossen',
    details: '',
  },
  {
    id: 5,
    title: 'Server-Backup',
    customer: customers[1],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-20'),
    dueDate: new Date('2025-10-23'),
    status: 'abgeschlossen',
    details: '',
  },
  {
    id: 6,
    title: 'Email-Archivierung',
    customer: customers[2],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-12'),
    dueDate: new Date('2025-10-19'),
    status: 'storniert',
    details: '',
  },
  {
    id: 7,
    title: 'Sicherheits-Analyse',
    customer: customers[3],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-11'),
    dueDate: new Date('2025-10-25'),
    status: 'abgeschlossen',
    details: '',
  },
  {
    id: 8,
    title: 'Server-Backup',
    customer: customers[3],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-9-30'),
    dueDate: new Date('2025-10-19'),
    status: 'abgeschlossen',
    details: '',
  },
  {
    id: 9,
    title: 'Anti-Phishing Training',
    customer: customers[4],
    items:
      '["Besprechung", "Planung & Vorbereitung", "Durchführung", "Nachbesprechung"]',
    orderDate: new Date('2025-10-10'),
    dueDate: new Date('2025-11-10'),
    status: 'in Bearbeitung',
    details: '',
  },
  {
    id: 10,
    title: 'ERP-System',
    customer: customers[4],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-18'),
    dueDate: new Date('2025-11-12'),
    status: 'in Bearbeitung',
    details: '',
  },
  {
    id: 11,
    title: 'Server-Backup',
    customer: customers[5],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 12,
    title: 'Datensicherung',
    customer: customers[5],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 13,
    title: 'Server-Backup',
    customer: customers[6],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 14,
    title: 'Email-Archivierung',
    customer: customers[6],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 15,
    title: 'Sicherheits-Analyse',
    customer: customers[7],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 16,
    title: 'Server-Backup',
    customer: customers[8],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 17,
    title: 'Nextcloud',
    customer: customers[8],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 18,
    title: 'Datensicherung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 19,
    title: 'IT-Beratung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 20,
    title: 'Email-Archivierung',
    customer: customers[9],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 21,
    title: 'Telefonanlage',
    customer: customers[10],
    items: '["Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 22,
    title: 'Microsoft 365',
    customer: customers[10],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 23,
    title: 'Anti-Phishing Training',
    customer: customers[10],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 24,
    title: 'Server-Backup',
    customer: customers[11],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 25,
    title: 'Sicherheits-Analyse',
    customer: customers[11],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 26,
    title: 'Telefonanlage',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 27,
    title: 'Sicherheits-Analyse',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 28,
    title: 'Server-Backup',
    customer: customers[12],
    items:
      '["Planung", "Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 29,
    title: 'Remote Desktop',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 30,
    title: 'Server-Backup',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 31,
    title: 'Nextcloud',
    customer: customers[13],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 32,
    title: 'Monitoring-System',
    customer: customers[14],
    items: '["Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
  {
    id: 33,
    title: 'Email-Archivierung',
    customer: customers[14],
    items: '["Entwicklung", "Installation vor Ort", "Konfiguration", "Testen"]',
    orderDate: new Date('2025-10-29'),
    dueDate: new Date('2025-11-19'),
    status: 'angelegt',
    details: '',
  },
];
